### PR TITLE
add an executable script, and document

### PR DESCRIPTION
**Pull request by MetaMemoryT**
This addresses https://github.com/hiddentao/gulp-server-livereload/issues/12

### CODE REVIEW

**Comment by hiddentao** [comment]
This is nice, though I'm not keen on how the arguments parsing is being done. Please rewrite that using [https://www.npmjs.com/package/commander](commander) as it will make life a lot easier.

**Comment by MetaMemoryT** [comment]
sure, didn't know if extra dep too much bloat for a gulp plugin.

**Comment by hiddentao** [comment]
`commander` has only one small dependency and is mostly self-contained. I think it's worth adding it in as it will make adding future CLI options easier too.

**Comment by MetaMemoryT** [comment]
Now the script uses `commander` for argument parsing.

**Comment by hiddentao** [comment]
I will look at this tomorrow. I think the README needs better documentation (e.g. output of the `--help` command) on this but I don't mind doing that myself.

**Pull request merged**
